name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install Surge
        run: npm install -g surge
      - name: Build site
        run: npm run build
      - name: Deploy to surge
        run: surge ./dist https://edheaver.surge.sh --token ${{secrets.SURGE_TOKEN}}
